//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by F:\open src\ScreenCapture\ScreenCapture\src\SCRes\SCRes.rc
//
#define IDS_SKIN_NAME_1                 1
#define IDS_SKIN_NAME_2                 2
#define IDS_FLOAT_TOOL_BK_COLOR_1       3
#define IDS_FLOAT_TOOL_FRAME_COLOR_1    4
#define IDS_TOOL_SELECT_TIP             5
#define IDS_TOOL_RECT_TIP               6
#define IDS_TOOL_ELLIPSE_TIP            7
#define IDS_TOOL_EXTEND_MENU_TIP        8
#define IDS_FLOAT_TOOL_BK_COLOR_2       9
#define IDS_TOOL_LINE_TIP               10
#define IDS_TOOL_PEN_TIP                11
#define IDS_TOOL_TEXT_TIP               12
#define IDS_DEFAULT_TEXT_FONT_NAME      13
#define IDS_TOOL_ERASER_TIP             14
#define IDS_TOOL_ARROW_TIP              15
#define IDS_MENU_TOOL                   16
#define IDS_MENU_SELECT                 17
#define IDS_MENU_RECT                   18
#define IDS_MENU_ELLIPSE                19
#define IDS_MENU_LINE                   20
#define IDS_MENU_ARROW                  21
#define IDS_MENU_PEN                    22
#define IDS_MENU_TEXT                   23
#define IDS_MENU_ERASER                 24
#define IDS_MENU_UNDO                   25
#define IDS_MENU_REDO                   26
#define IDS_MENU_SKIN                   27
#define IDS_MENU_HELP_TIP               28
#define IDS_MENU_SAVE                   29
#define IDS_COPY_EXIT                   30
#define IDS_START_CAPTURE               31
#define IDS_CLOSE_BTN_TIP               32
#define IDS_SAVE_DLG_TITLE              33
#define IDS_SAVE_FILE_DEF_NAME          34
#define IDS_MENU_EXIT                   35
#define IDS_HELP_TIP_FORMAT             36
#define IDS_MENU_DOUBLE_CLICK_EXIT      37
#define IDS_TOOL_WIN_SELECT_TIP         38
#define IDS_MENU_WIN_SELECT             39
#define IDS_MENU_SHOW_CURSOR            40
#define IDS_LAN_NAME_1                  41
#define IDS_LAN_NAME_2                  42
#define IDS_MENU_LAN                    43
#define IDS_IMAGE_COPY_TIP              44
#define IDS_IMAGE_COPY_TIP2             45
#define IDS_TRANSPARENT_ANNOTATION      46
#define IDS_ABOUT                       47
#define IDS_ABOUT_TITLE                 48
#define IDS_SETTING                     49
#define IDS_SETTING_TITLE               50
#define IDS_MENU_SAVE_EDIT              51
#define IDB_CANVAS_SHADOW_1             101
#define IDB_CANVAS_SHADOW_2             102
#define IDB_WATER_MARK_1                103
#define IDB_WATER_MARK_2                104
#define IDB_TOOL_SEP_BK                 105
#define IDB_TOOL_BTN_BK                 106
#define IDB_TOOL_BTN_SELECT             107
#define IDB_FLOAT_MENU_1                108
#define IDB_FLOAT_DRAG_BK_1             109
#define IDB_FLOAT_DRAG_1                110
#define IDB_FLOAT_MENU_BK_1             111
#define IDB_TOOL_BTN_RECT_1             112
#define IDB_TOOL_BTN_ELLIPSE_1          113
#define IDB_FLOAT_MENU_2                114
#define IDB_BTN_PEN_SMALL1              115
#define IDB_BTN_PEN_BIG1                116
#define IDB_BTN_PEN_BK1                 117
#define IDB_BTN_PEN_MIDDLE1             118
#define IDB_TOOL_BTN_LINE_1             119
#define IDB_TOOL_BTN_PEN_1              120
#define IDB_TOOL_BTN_TEXT_1             121
#define IDB_BTN_FONT_BOLD_1             122
#define IDB_TOOL_BTN_ERASER_1           123
#define IDB_TOOL_BTN_ARROW_1            124
#define IDC_DEFAULT_CURSOR              125
#define IDC_PEN_CURSOR                  126
#define IDC_ERASER_CURSOR               127
#define IDC_SELECT_CURSOR               129
#define IDB_START_BTN_BK_1              130
#define IDB_START_BTN_1                 131
#define IDB_CLOSE_BTN_BK_1              132
#define IDB_CLOSE_BTN_1                 133
#define IDB_FLOAT_DRAG_2                134
#define IDB_FLOAT_DRAG_BK_2             135
#define IDB_FLOAT_TOOL_BK_1             136
#define IDB_FLOAT_MENU_BK_2             137
#define IDB_FLOAT_TOOL_BK_2             138
#define IDB_TOOL_BTN_BK_2               139
#define IDB_TOOL_BTN_SELECT_2           140
#define IDB_TOOL_SEP_BK_2               141
#define IDB_TOOL_BTN_RECT_2             142
#define IDB_TOOL_BTN_ELLIPSE_2          143
#define IDB_TOOL_BTN_LINE_2             144
#define IDB_TOOL_BTN_ARROW_2            145
#define IDB_TOOL_BTN_PEN_2              146
#define IDB_TOOL_BTN_TEXT_2             147
#define IDB_TOOL_BTN_ERASER_2           148
#define IDB_SUB_FLOAT_TOOL_BK_2         149
#define IDB_SUB_FLOAT_TOOL_BK_1         150
#define IDB_BTN_PEN_BK_2                151
#define IDB_BTN_PEN_SMALL_2             152
#define IDB_BTN_PEN_MIDDLE_2            153
#define IDB_BTN_PEN_BIG_2               154
#define IDB_BTN_FONT_BOLD_2             155
#define IDB_MENU_CHECK_BOX_1            156
#define IDB_MENU_CHECK_BOX_2            157
#define IDB_TOOL_BTN_WIN_SELECT1        158
#define IDB_TOOL_BTN_WIN_SELECT2        159
#define IDB_INFO_BUBBLE_BK_1            161
#define IDD_ABOUT                       161
#define IDB_INFO_BUBBLE_BK_2            162
#define IDB_TITLE_BK_1                  163
#define IDB_TITLE_BK_2                  164
#define IDB_ABOUT_WAVE_BK               166
#define IDD_ABOUT_INFO                  167
#define IDB_DLG_BTN_IMG                 168
#define IDD_SAVE_IMAGE                  168
#define IDB_DLG_BTN_BK                  169
#define IDD_SETTING                     170
#define IDC_SITE                        1001
#define IDC_CHECK_SHOW_ZOOM             1002
#define IDC_CHECK_SHOW_CURSOR           1003
#define IDC_CHECK_CLOSE_SCREEN_CAPTURE  1003
#define IDC_CHECK_TRANSPARENT_MARK      1004
#define IDC_CHECK_DBCLICK_CLOSE         1005
#define IDC_EDIT_IMAGE_EDITOR           1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        169
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
