//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SmsClient.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_DETAIL                      201
#define IDB_SMS_BOX                     202
#define IDB_SMS_MESSSAGE                203
#define IDR_VIEW_LIST                   204
#define IDR_VIEW_CURRENT                206
#define IDD_SPLASH                      207
#define IDD_SETTING                     208
#define IDB_SMS_CONTACT                 209
#define IDD_CONTACT_MANAGER             210
#define IDR_CONTACT                     211
#define IDD_TEAM                        213
#define IDD_CONTACT                     214
#define IDD_TRANSFER                    215
#define IDD_SEND                        216
#define IDD_ADD_TEL                     217
#define IDR_SEND_LIST                   218
#define IDD_SEARCH                      219
#define IDD_MESSAGE_LIB                 220
#define IDB_MESSAGE_LIB                 221
#define IDR_MESSAGE_LIB                 222
#define IDD_MESSAGE                     224
#define IDD_READ_MSG                    225
#define IDB_INFORMATION                 226
#define IDB_CLOSE                       227
#define IDI_CONNECTED                   228
#define IDI_DISCONNECTED                229
#define IDI_CONNECTING                  230
#define IDB_HUMAN                       243
#define IDB_MSG                         246
#define IDI_CONNECTED_TRAY              247
#define IDI_CONNECTING_TRAY             248
#define IDI_DISCONNECTED_TRAY           249
#define IDB_SPLASH                      250
#define IDD_INFORMATION                 251
#define IDD_IMPORT_EXCEL                252
#define IDD_EXPORT_XML                  253
#define IDD_IMPORT_XML                  254
#define IDC_CONTACT_NAME                1000
#define IDC_CONTACT_CAPTION             1001
#define IDC_TIME_CAPTION                1002
#define IDC_TIME_VALUE                  1003
#define IDC_CONTENT                     1004
#define IDC_NAME                        1006
#define IDC_PASSWORD                    1007
#define IDC_SERVER                      1008
#define IDC_PORT                        1009
#define IDC_AUTO_INFO                   1010
#define IDC_AUTO_CON                    1011
#define IDC_OK                          1012
#define IDC_CANCEL                      1013
#define IDC_TEAM                        1018
#define IDC_TEL                         1020
#define IDC_CONTACT                     1026
#define IDC_ADD                         1027
#define IDC_NEW                         1028
#define IDC_DELETE                      1029
#define IDC_CLEAR                       1030
#define IDC_RECEIVER                    1031
#define IDC_ON_TIMER                    1032
#define IDC_TIME                        1033
#define IDC_MESSAGE_COUNT               1035
#define IDC_SEND                        1037
#define IDC_CLOSE                       1038
#define IDC_CHARACTER_COUNT             1039
#define IDC_DATE                        1041
#define IDC_BOX                         1045
#define IDC_CHECK_NAME                  1046
#define IDC_CHECK_TEL                   1048
#define IDC_CHECK_CONTENT               1050
#define IDC_SEARCH                      1052
#define IDC_MESSAGE                     1055
#define IDC_TYPE                        1056
#define IDC_INSERT_CONTENT              1060
#define IDC_REPLY                       1063
#define IDC_TRANSFER                    1064
#define IDC_SAVE                        1065
#define IDC_INFO                        1067
#define IDC_PROGRESS                    1070
#define IDC_EMAIL                       1074
#define IDC_QQ                          1075
#define IDC_SHEET                       1076
#define IDC_IMPORT                      1085
#define IDC_ALL_CHECK                   1089
#define IDC_EXPORT                      1091
#define IDC_FILE                        1093
#define IDC_EXPLORE                     1094
#define IDC_TREE                        1096
#define ID_SYSTEM_CONNECT               32773
#define ID_SYSTEM_DISCONNECT            32774
#define ID_SYSTEM_SETTING               32775
#define ID_SMS_NEW                      32776
#define ID_SMS_REPLY                    32777
#define ID_SMS_TRANSFER                 32778
#define ID_SMS_DELETE                   32780
#define ID_SMS_SEARCH                   32781
#define ID_SYSTEM_EXIT                  32782
#define ID_TOOL_CONTACTLIST             32783
#define ID_TOOL_SMSLIB                  32784
#define ID_HELP_ABOUT                   32785
#define ID_VIEW_STATUSBAR               32786
#define ID_VIEW_SMSBOX                  32787
#define ID_VIEW_CONTACTLIST             32788
#define ID_VIEW_CONTENT                 32789
#define ID_VIEW_BOX                     32790
#define ID_VIEW_CURRENT                 32792
#define ID_VIEW_TOSEND                  32794
#define ID_VIEW_SENDED                  32795
#define ID_VIEW_RECEIVED                32796
#define ID_VIEW_DELETED                 32797
#define ID_ADD_TEAM                     32800
#define ID_MODIFY_TEAM                  32801
#define ID_DELETE_TEAM                  32802
#define ID_ADD_CONTACT                  32803
#define ID_MODIFY_CONTACT               32804
#define ID_DELETE_CONTACT               32805
#define ID_TRANSFER_CONTACT             32806
#define ID_EXIT                         32807
#define ID_NEW                          32812
#define ID_DELETE                       32813
#define ID_CLEAR                        32814
#define ID_SMS_CLEAR                    32815
#define ID_ADD_TYPE                     32816
#define ID_DELETE_TYPE                  32817
#define ID_MODIFY_TYPE                  32818
#define ID_ADD_MESSAGE                  32819
#define ID_MODIFY_MESSAGE               32820
#define ID_DELETE_MESSAGE               32821
#define ID_TRANSFER_MESSAGE             32822
#define IS_SMS_SAVE                     32823
#define ID_SMS_SAVE                     32824
#define ID_INSERT_CONTENT               32825
#define ID_SMS_GETTEL                   32826
#define ID_SYSTEM_SHOW                  32827
#define ID_HELP_QUESTION                32830
#define ID_IMPORT                       32831
#define ID_EXPORT                       32836
#define ID_SEND_MSG                     50000
#define IDS_SMS_BOX                     61403
#define IDS_SMS_CONTACT                 61404
#define IDS_BOX_TOSEND                  61405
#define IDS_BOX_SENDED                  61406
#define IDS_BOX_RECEIVED                61407
#define IDS_BOX_DELETED                 61408
#define IDS_BOX_SERVER                  61409
#define IDS_COMPANY_INFO                61410

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        255
#define _APS_NEXT_COMMAND_VALUE         32837
#define _APS_NEXT_CONTROL_VALUE         1102
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
